import {useEffect,useState} from 'react';
import {useProfile} from '@/components/AuthGate';
import {accountApi} from '@/lib/beta-api';
type Member={id:string;email:string;created_at:string;revoked:boolean;confirmed:boolean;requested:number;completed:number;saved:number};
type Overview={totalUsers:number;totalReports:number;users:Member[];activity:{id:string;email:string;kind:string;subject:string;status:string;created_at:string}[];assets:{kind:string;subject:string;reports:number}[]};
const labels:Record<string,string>={ticker:'Acción',etf:'ETF',sector:'Sector',started:'En curso',completed:'Completado',failed:'Fallido',cancelled:'Cancelado'};
export default function Admin(){const profile=useProfile();const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[page,setPage]=useState(0),[targetId,setTargetId]=useState<string|null>(null),[version,setVersion]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!profile.isAdmin)return;let active=true;setError('');accountApi<Overview>('adminOverview',{page,targetId}).then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[profile.isAdmin,page,targetId,version]);
  async function toggle(user:Member){if(!window.confirm(`${user.revoked?'Restaurar':'Revocar'} el acceso de ${user.email}?`))return;setBusy(true);try{await accountApi('adminRevoke',{targetId:user.id,revoked:!user.revoked});setVersion(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!profile.isAdmin)return <p className="p-8">No tienes permiso para acceder a este apartado.</p>;
  return <main className="max-w-7xl mx-auto p-5 space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-xl text-primary">Administración de la beta</h1><p className="text-sm mt-2">{data?.totalUsers??'—'} registros · {data?.totalReports??'—'} informes solicitados</p></div><button className="border border-border px-4 py-2" onClick={()=>setVersion(n=>n+1)}>Actualizar</button></div>
    <p className="text-sm text-muted-foreground">Límites: 20 informes por cuenta al día, uno simultáneo y 200 diarios para toda la beta. Hasta 100 informes guardados por cuenta. Los fallidos y cancelados también cuentan para limitar el gasto.</p>
    {error&&<p role="alert" className="text-destructive">{error}</p>}
    <section><h2 className="text-primary mb-3">Usuarios registrados</h2><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['E-mail','Registro','Estado','Solicitados / completados','Guardados','Acceso'].map(v=><th className="p-3" key={v}>{v}</th>)}</tr></thead><tbody>{data?.users.map(u=><tr key={u.id} className="border-t border-border"><td className="p-3"><button className="text-primary underline" onClick={()=>setTargetId(u.id)}>{u.email}</button></td><td className="p-3">{new Date(u.created_at).toLocaleDateString('es-ES')}</td><td className="p-3">{u.revoked?'Revocado':u.confirmed?'Activo':'E-mail pendiente'}</td><td className="p-3">{u.requested} / {u.completed}</td><td className="p-3">{u.saved}</td><td className="p-3">{u.id===profile.id?'Administrador':<button disabled={busy} className="border border-border px-3 py-2" onClick={()=>toggle(u)}>{u.revoked?'Restaurar':'Revocar'}</button>}</td></tr>)}</tbody></table></div><div className="flex gap-4 mt-3"><button disabled={page===0} onClick={()=>setPage(n=>n-1)}>Anterior</button><span>Página {page+1}</span><button disabled={!data||(page+1)*50>=data.totalUsers} onClick={()=>setPage(n=>n+1)}>Siguiente</button></div></section>
    <section><div className="flex gap-4 mb-3"><h2 className="text-primary">Actividad reciente {targetId?'del usuario seleccionado':''}</h2>{targetId&&<button onClick={()=>setTargetId(null)}>Ver todos</button>}</div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Fecha','E-mail','Tipo','Activo','Estado'].map(v=><th className="p-3" key={v}>{v}</th>)}</tr></thead><tbody>{data?.activity.map(a=><tr key={a.id} className="border-t border-border"><td className="p-3">{new Date(a.created_at).toLocaleString('es-ES')}</td><td className="p-3">{a.email}</td><td className="p-3">{labels[a.kind]}</td><td className="p-3">{a.subject}</td><td className="p-3">{labels[a.status]}</td></tr>)}</tbody></table></div><p className="text-xs text-muted-foreground mt-2">Últimas 100 solicitudes. Pulsa un e-mail para filtrar por usuario.</p></section>
    <section><h2 className="text-primary mb-3">Activos analizados</h2><div className="grid sm:grid-cols-3 gap-3">{data?.assets.map(a=><div key={a.kind+a.subject} className="border border-border p-3 text-sm">{labels[a.kind]} · {a.subject}<span className="float-right">{a.reports}</span></div>)}</div></section>
  </main>;
}
