import {ComparisonExtras,CorrelationExtras,type ExtraAsset,type RiskMetrics} from "@/components/AnalyticsExtras";
import { useMemo, useState } from "react";
import { AlertCircle, Loader2, RefreshCw } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Bar, BarChart } from "recharts";
import { authenticatedFetch } from "@/lib/beta-api";

const ENDPOINT=`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/analyze-ticker`;
const COLORS=["#18d978","#38bdf8","#c084fc","#fbbf24","#fb7185","#a3e635","#f97316","#22d3ee","#e879f9","#94a3b8","#f43f5e"];
type ComparisonRow=ExtraAsset&{symbol:string;available:boolean;lastTradeDate?:string;price?:number;change1d?:number|null;change1m?:number|null;volume?:number|null;dollarVolume?:number|null;avgVolume20?:number|null;volumeVsAverage?:number|null;netFundFlows?:number|null;dates?:number[];closes?:number[]};
type ComparisonData={assets:ComparisonRow[];flowNote:string;fetchedAt:string};
type CorrelationData={missing?:string[];metrics?:RiskMetrics[];rolling?:Record<string,string|number|null>[];drawdowns?:Record<string,string|number|null>[];symbols:string[];correlation:(number|null)[][];observations:number;chart:Record<string,string|number|null>[];range:string;fetchedAt:string};
const pct=(v:number|null|undefined)=>v==null?"—":`${v>0?"+":""}${v.toFixed(2)}%`;
const compact=(v:number|null|undefined)=>v==null?"—":Intl.NumberFormat("es-ES",{notation:"compact",maximumFractionDigits:2}).format(v);

export default function MarketTools(){

  const [symbols,setSymbols]=useState("");
  const [compare,setCompare]=useState<ComparisonData|null>(null);
  const [corrSymbols,setCorrSymbols]=useState("");
  const [range,setRange]=useState("3m");
  const [corr,setCorr]=useState<CorrelationData|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const parsed=useMemo(()=>[...new Set(symbols.toUpperCase().split(/[\s,;]+/).map(x=>x.trim()).filter(Boolean))].slice(0,12),[symbols]);
  const parsedCorr=useMemo(()=>[...new Set(corrSymbols.toUpperCase().split(/[\s,;]+/).map(x=>x.trim()).filter(Boolean))].slice(0,6),[corrSymbols]);
  async function load(panel:"comparison"|"correlation"){
    setBusy(true);setError("");
    try{const response=await authenticatedFetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(panel==="comparison"?{panel,symbols:parsed}:{panel,symbols:parsedCorr,range}),signal:AbortSignal.timeout(45000)});const data=await response.json();if(!response.ok)throw new Error(data.error||"No se han podido cargar los datos.");if(panel==="comparison")setCompare(data);else setCorr(data);}
    catch(e){setError(e instanceof Error?e.message:"No se han podido cargar los datos.");}finally{setBusy(false);}
  }
  const chartRows=useMemo(()=>{if(!corr)return[];return corr.chart.map(row=>({...row,date:new Date(`${row.date}T00:00:00`).toLocaleDateString("es-ES",{day:"2-digit",month:"short"})}));},[corr]);
  const comparisonChart=useMemo(()=>{if(!compare)return[];const dates=new Map<number,Record<string,string|number|null>>();for(const asset of compare.assets){if(!asset.dates||!asset.closes?.length)continue;const start=asset.closes[0];asset.dates.forEach((time,i)=>{const row=dates.get(time)??{date:new Date(time*1000).toLocaleDateString("es-ES",{day:"2-digit",month:"short"})};row[asset.symbol]=start?+((asset.closes![i]/start-1)*100).toFixed(2):null;dates.set(time,row);});}return [...dates.entries()].sort((a,b)=>a[0]-b[0]).map(([,row])=>row);},[compare]);
  return <main className="max-w-7xl mx-auto px-4 py-7 space-y-5">
    <h1 className="text-xl font-semibold">Comparación y correlación de activos</h1>
    {error&&<p role="alert" className="border border-destructive/40 p-3 text-sm text-destructive flex gap-2"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</p>}
    <section className="space-y-5"><h2 className="text-primary text-sm">COMPARACIÓN · RENTABILIDAD Y ACTIVIDAD</h2>
      <div className="border border-border bg-card p-4 space-y-3"><label className="text-xs tracking-wide block"><span className="sr-only">Activos para comparar, separados por comas; máximo 12</span><textarea aria-label="Activos para comparar" placeholder="Escribe los tickers separados por comas" rows={2} value={symbols} onChange={e=>setSymbols(e.target.value)} className="mt-2 w-full resize-y bg-background border border-border px-3 py-2 text-sm"/></label><button disabled={busy||parsed.length<2} onClick={()=>void load("comparison")} className="inline-flex items-center gap-2 bg-primary text-black px-4 py-2 text-xs font-bold tracking-widest disabled:opacity-50">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:<RefreshCw className="w-4 h-4"/>} ACTUALIZAR COMPARACIÓN</button></div>
      {!compare?<p className="text-sm text-muted-foreground py-12 text-center border border-border">Carga la comparación para ver rentabilidad, volumen y actividad diaria.</p>:<>
        <div className="grid lg:grid-cols-2 gap-4"><div className="border border-border bg-card p-4"><h2 className="text-xs tracking-widest mb-4">RENDIMIENTO AJUSTADO · ÚLTIMOS 6 MESES</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={comparisonChart}><CartesianGrid stroke="#26303b" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={25} tick={{fontSize:9}}/><YAxis tick={{fontSize:9}} unit="%"/><Tooltip/><Legend/><Line dataKey="_hide" hide/>{compare.assets.filter(a=>a.available&&a.dates&&a.closes).map((a,i)=><Line key={a.symbol} dataKey={a.symbol} name={a.symbol} stroke={COLORS[i%COLORS.length]} dot={false} connectNulls={false} type="linear"/> )}</LineChart></ResponsiveContainer></div></div>
          <div className="border border-border bg-card p-4"><h2 className="text-xs tracking-widest mb-4">VOLUMEN NEGOCIADO · MONEDA DEL ACTIVO</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={compare.assets.filter(a=>a.available).map(a=>({symbol:a.symbol,usd:a.dollarVolume??null}))}><CartesianGrid stroke="#26303b" strokeDasharray="3 3"/><XAxis dataKey="symbol" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}} tickFormatter={compact}/><Tooltip formatter={(v:number)=>`$${compact(v)}`}/><Bar dataKey="usd" name="Última sesión" fill="#18d978"/></BarChart></ResponsiveContainer></div></div></div>
        <div className="overflow-x-auto border border-border"><table className="w-full text-xs"><thead className="bg-card text-muted-foreground"><tr>{["ETF","Fecha último dato","Precio","1 día","1 mes","Volumen","Importe negociado","Media 20d","vs media","Flujos netos del fondo"].map(x=><th key={x} className="p-3 text-left font-normal whitespace-nowrap">{x}</th>)}</tr></thead><tbody>{compare.assets.map(a=><tr key={a.symbol} className="border-t border-border"><td className="p-3 font-semibold">{a.symbol}</td><td className="p-3">{a.lastTradeDate??"—"}</td><td className="p-3">{a.price==null?"—":`${a.price.toFixed(2)} ${a.currency??""}`}</td><td className="p-3">{pct(a.change1d)}</td><td className="p-3">{pct(a.change1m)}</td><td className="p-3">{compact(a.volume)}</td><td className="p-3">{a.dollarVolume==null?"—":`${compact(a.dollarVolume)} ${a.currency??""}`}</td><td className="p-3">{compact(a.avgVolume20)}</td><td className="p-3">{a.volumeVsAverage==null?"—":`${a.volumeVsAverage.toFixed(2)}×`}</td><td className="p-3 text-muted-foreground">{a.netFundFlows==null?"No disponible":`$${compact(a.netFundFlows)}`}</td></tr>)}</tbody></table></div>
        <ComparisonExtras assets={compare.assets}/><p className="text-xs text-muted-foreground">{compare.flowNote} Actividad consultada: {new Date(compare.fetchedAt).toLocaleString("es-ES")}.</p>
      </>}
    </section><section className="space-y-5 border-t border-border pt-6"><h2 className="text-primary text-sm">CORRELACIÓN · RIESGO Y DIVERSIFICACIÓN</h2>
      <div className="border border-border bg-card p-4 flex flex-col sm:flex-row gap-3 items-end"><label className="text-xs flex-1 w-full">Activos, separados por comas (2–6)<input aria-label="Activos para correlación" value={corrSymbols} onChange={e=>setCorrSymbols(e.target.value)} className="mt-2 w-full bg-background border border-border px-3 py-2 text-sm"/></label><label className="text-xs">Ventana<select aria-label="Ventana de correlación" value={range} onChange={e=>setRange(e.target.value)} className="mt-2 block bg-background border border-border px-3 py-2"><option value="1m">1 mes</option><option value="3m">3 meses</option><option value="6m">6 meses</option><option value="1y">1 año</option></select></label><button disabled={busy||parsedCorr.length<2} onClick={()=>void load("correlation")} className="inline-flex items-center gap-2 bg-primary text-black px-4 py-2 text-xs font-bold tracking-widest disabled:opacity-50">{busy?<Loader2 className="w-4 h-4 animate-spin"/>:<RefreshCw className="w-4 h-4"/>} CALCULAR</button></div>
      {!corr?<p className="text-sm text-muted-foreground py-12 text-center border border-border">Elige activos y período. SPY (S&P 500) y URTH (MSCI World) se incluyen automáticamente como referencias.</p>:<><div className="border border-border bg-card p-4"><h2 className="text-xs tracking-widest mb-4">RENDIMIENTO NORMALIZADO · {corr.range.toUpperCase()} · {corr.observations} SESIONES</h2><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartRows}><CartesianGrid stroke="#26303b" strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={25} tick={{fontSize:9}}/><YAxis tick={{fontSize:9}} unit="%"/><Tooltip/><Legend/>{corr.symbols.map((s,i)=><Line key={s} dataKey={s} stroke={COLORS[i%COLORS.length]} dot={false} type="monotone"/> )}</LineChart></ResponsiveContainer></div></div>
        <div className="overflow-x-auto border border-border"><table className="w-full text-xs text-center"><thead><tr><th className="p-3 text-left">Correlación</th>{corr.symbols.map(s=><th key={s} className="p-3">{s}</th>)}</tr></thead><tbody>{corr.symbols.map((s,i)=><tr key={s} className="border-t border-border"><th className="p-3 text-left">{s}</th>{corr.symbols.map((t,j)=>{const value=corr.correlation[i]?.[j];return <td key={t} className="p-3 tabular-nums" style={{background:value==null?undefined:`rgba(${value>=0?24:248},${value>=0?217:113},${value>=0?120:113},${Math.min(.35,Math.abs(value)*.35)})`}}>{value==null?"—":value.toFixed(2)}</td>;})}</tr>)}</tbody></table></div><p className="text-xs text-muted-foreground">Correlación de Pearson calculada sobre rendimientos ajustados de sesiones coincidentes. Datos: {new Date(corr.fetchedAt).toLocaleString("es-ES")}.</p><CorrelationExtras data={corr}/></>}
    </section>
  </main>;
}
