import {CartesianGrid,Legend,Line,LineChart,BarChart,Bar,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
const COLORS=['#18d978','#38bdf8','#c084fc','#fbbf24','#fb7185','#a3e635','#f97316','#22d3ee'];
export type RiskMetrics={symbol:string;volatility?:number|null;maxDrawdown?:number|null;totalReturn?:number|null;betaSP500?:number|null;correlationSP500?:number|null;correlationWorld?:number|null;trackingErrorSP500?:number|null};
type Holding={period:string;shares:number|null;sharesChange:number|null;investors:number|null;value:number|null};
export type ExtraAsset=RiskMetrics&{available:boolean;currency?:string;change3m?:number|null;institutions?:Holding[];monthlyActivity?:{month:string;value:number}[]};
type ChartRow=Record<string,string|number|null>;
const n=(v:number|null|undefined,d=2)=>v==null?'—':v.toLocaleString('es-ES',{maximumFractionDigits:d});
const percent=(v:number|null|undefined)=>v==null?'—':n(v)+'%';
export function ComparisonExtras({assets}:{assets:ExtraAsset[]}){
  return <div className="space-y-4"><div className="grid md:grid-cols-2 gap-4"><div className="border border-border p-4"><h2 className="text-xs mb-3 tracking-widest">VOLATILIDAD ANUALIZADA · 6 MESES</h2><div className="h-64"><ResponsiveContainer><BarChart data={assets.filter(a=>a.volatility!=null)}><CartesianGrid stroke="#26303b"/><XAxis dataKey="symbol" tick={{fontSize:9}}/><YAxis unit="%"/><Tooltip formatter={(v:number)=>percent(v)}/><Bar dataKey="volatility" name="Volatilidad" fill="#38bdf8"/></BarChart></ResponsiveContainer></div></div><div className="border border-border p-4"><h2 className="text-xs mb-3 tracking-widest">CAÍDA MÁXIMA · 6 MESES</h2><div className="h-64"><ResponsiveContainer><BarChart data={assets.filter(a=>a.maxDrawdown!=null)}><CartesianGrid stroke="#26303b"/><XAxis dataKey="symbol" tick={{fontSize:9}}/><YAxis unit="%"/><Tooltip formatter={(v:number)=>percent(v)}/><Bar dataKey="maxDrawdown" name="Caída desde máximo" fill="#fb7185"/></BarChart></ResponsiveContainer></div></div></div>
    <div className="border border-border overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{['Activo','Rentabilidad 3m','Rentabilidad 6m','Volatilidad anualizada','Caída máxima'].map(h=><th key={h} className="p-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{assets.map(a=><tr key={a.symbol} className="border-t border-border"><td className="p-3">{a.symbol}</td><td className="p-3">{percent(a.change3m)}</td><td className="p-3">{percent(a.totalReturn)}</td><td className="p-3">{percent(a.volatility)}</td><td className="p-3">{percent(a.maxDrawdown)}</td></tr>)}</tbody></table></div>
    <div className="border border-border p-4"><h2 className="text-xs tracking-widest mb-4">ACTIVIDAD MENSUAL · IMPORTE NEGOCIADO</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{assets.filter(a=>a.available).map(a=><div key={a.symbol} className="border border-border p-3"><b className="text-xs text-primary">{a.symbol} · {a.currency}</b>{a.monthlyActivity?.map(m=><p key={m.month} className="text-xs flex justify-between gap-3 mt-2"><span>{m.month}</span><span>{Intl.NumberFormat('es-ES',{notation:'compact',maximumFractionDigits:2}).format(m.value)}</span></p>)}</div>)}</div><p className="text-xs text-muted-foreground mt-3">Suma de volumen × cierre diario. El mes actual puede estar incompleto. Es actividad negociada, no entradas de capital.</p></div>
    <div className="border border-border p-4"><h2 className="text-xs tracking-widest mb-4">CAMBIOS EN POSICIONES INSTITUCIONALES · ÚLTIMOS TRIMESTRES</h2><div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{['Activo','Período','Participaciones declaradas','Cambio de participaciones','Instituciones'].map(h=><th key={h} className="p-2 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{assets.flatMap(a=>a.institutions?.length?a.institutions.map(h=><tr key={a.symbol+h.period} className="border-t border-border"><td className="p-2">{a.symbol}</td><td className="p-2">{h.period}</td><td className="p-2">{n(h.shares,0)}</td><td className="p-2">{n(h.sharesChange,0)}</td><td className="p-2">{n(h.investors,0)}</td></tr>):[<tr key={a.symbol} className="border-t border-border"><td className="p-2">{a.symbol}</td><td colSpan={4} className="p-2 text-muted-foreground">Sin declaraciones disponibles con el acceso actual.</td></tr>])}</tbody></table></div></div>
  </div>;
}
function HistoryChart({title,rows,symbols,correlation=false}:{title:string;rows:ChartRow[];symbols:string[];correlation?:boolean}){
  return <div className="border border-border p-4"><h2 className="text-xs tracking-widest mb-4">{title}</h2>{rows.length?<div className="h-64"><ResponsiveContainer><LineChart data={rows}><CartesianGrid stroke="#26303b"/><XAxis dataKey="date" tick={{fontSize:9}} minTickGap={30}/><YAxis domain={correlation?[-1,1]:['auto','auto']} unit={correlation?'':'%'}/><Tooltip formatter={(v:number)=>n(v)}/><Legend/>{symbols.map((s,i)=><Line key={s} dataKey={s} stroke={COLORS[i%COLORS.length]} dot={false} type="linear" connectNulls={false}/>)}</LineChart></ResponsiveContainer></div>:<p className="text-xs text-muted-foreground">Se necesitan al menos 20 sesiones comunes para esta ventana.</p>}</div>;
}
export function CorrelationExtras({data}:{data:{symbols:string[];missing?:string[];metrics?:RiskMetrics[];rolling?:ChartRow[];drawdowns?:ChartRow[]}}){
 return <div className="space-y-4"><p className="text-xs text-muted-foreground">Referencias: SPY representa al S&P 500 y URTH al MSCI World. Son ETF, con gastos y posibles diferencias frente al índice. Rendimientos ajustados en la moneda de cada activo; sin conversión de divisas.</p>{!!data.missing?.length&&<p role="status" className="text-sm text-amber-300">Sin histórico disponible: {data.missing.join(', ')}.</p>}<div className="grid lg:grid-cols-2 gap-4"><HistoryChart title="CORRELACIÓN MÓVIL CON S&P 500 · 20 SESIONES" rows={data.rolling??[]} symbols={data.symbols.filter(s=>s!=='SPY')} correlation/><HistoryChart title="CAÍDAS DESDE MÁXIMOS" rows={data.drawdowns??[]} symbols={data.symbols}/></div><div className="overflow-x-auto border border-border"><table className="w-full text-xs text-left"><thead><tr>{['Activo','Rentabilidad','Volatilidad anualizada','Caída máxima','Beta S&P 500','Correlación S&P 500','Correlación MSCI World','Tracking error S&P 500'].map(h=><th key={h} className="p-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{data.metrics?.map(m=><tr key={m.symbol} className="border-t border-border"><td className="p-3">{m.symbol}</td>{[percent(m.totalReturn),percent(m.volatility),percent(m.maxDrawdown),n(m.betaSP500),n(m.correlationSP500),n(m.correlationWorld),percent(m.trackingErrorSP500)].map((v,i)=><td key={i} className="p-3">{v}</td>)}</tr>)}</tbody></table></div><p className="text-xs text-muted-foreground">Beta mide sensibilidad al mercado; tracking error, la variación de la diferencia de retornos frente a SPY. Volatilidad y tracking error anualizados con 252 sesiones.</p></div>;
}
