import AssetRisk from './AssetRisk';
import {useEffect,useMemo,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,Legend,CartesianGrid} from 'recharts';
import {authenticatedFetch} from '@/lib/beta-api';
import {assetPerformance} from '@/lib/asset-performance';
import type {AssetContext as Context} from '../../../supabase/functions/analyze-ticker/asset-context';
const sectors:Record<string,string>={XLC:'Comunicación',XLY:'Consumo discrecional',XLP:'Consumo básico',XLE:'Energía',XLF:'Finanzas',XLV:'Salud',XLI:'Industria',XLK:'Tecnología',XLB:'Materiales',XLRE:'Inmobiliario',XLU:'Servicios públicos'};
const eventNames={earnings:'Resultados empresariales',ex_dividend:'Fecha exdividendo',payment:'Pago de dividendo'};
const colors=['#22d3a0','#60a5fa','#fbbf24'];
export default function AssetContext({symbol}:{symbol:string}){
 const [data,setData]=useState<Context|null>(null),[benchmark,setBenchmark]=useState('auto'),[days,setDays]=useState(90),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setBusy(true);setError('');setData(null);authenticatedFetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/analyze-ticker`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({panel:'assetContext',subject:symbol,...(benchmark==='auto'?{}:{benchmark})}),signal:AbortSignal.timeout(40000)}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(active)setData(d);}).catch(()=>{if(active)setError('No se han podido cargar el riesgo y la comparación. Cambia la referencia o vuelve a abrir la ficha para reintentar.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[symbol,benchmark]);
 const performance=useMemo(()=>assetPerformance(data?.series??[],symbol,days),[data,symbol,days]),last=performance.rows.at(-1),spy=Number(last?.SPY),own=Number(last?.[symbol]);
 return <><AssetRisk data={data?.risk} busy={busy} error={error}/>
 <section className="rounded-lg border border-border bg-card p-5 space-y-4"><div className="flex flex-wrap gap-3 justify-between"><h2 className="text-sm font-semibold">RENDIMIENTO FRENTE AL MERCADO Y SECTOR</h2><select aria-label="Referencia sectorial" value={benchmark} onChange={e=>setBenchmark(e.target.value)} className="border border-border bg-background text-xs p-2 rounded"><option value="auto">Sector automático</option><option value="">Solo S&P 500</option>{Object.entries(sectors).map(([s,n])=><option key={s} value={s}>{n} · {s}</option>)}</select></div>{data&&!data.benchmark&&<p className="text-xs text-muted-foreground">Selecciona un ETF sectorial si quieres añadir una referencia específica.</p>}<div className="flex gap-2">{[30,90,180,365].map(d=><button key={d} aria-pressed={days===d} className={`text-xs rounded px-3 py-2 ${days===d?'bg-primary/15 text-primary':'bg-muted'}`} onClick={()=>setDays(d)}>{({30:'1 MES',90:'3 MESES',180:'6 MESES',365:'1 AÑO'})[d]}</button>)}</div>
 {last&&<div className="flex flex-wrap gap-5 text-sm">{performance.symbols.map((s,i)=><div key={s}><p className="text-xs text-muted-foreground">{s==='SPY'?'S&P 500 · SPY':s}</p><b style={{color:colors[i]}}>{Number(last[s]).toFixed(2)}%</b></div>)}{Number.isFinite(spy)&&Number.isFinite(own)&&symbol!=='SPY'&&<div><p className="text-xs text-muted-foreground">Diferencia frente a SPY</p><b>{(own-spy).toFixed(2)} pp</b></div>}</div>}
 {performance.rows.length>1?<div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={performance.rows}><CartesianGrid stroke="#25332e" strokeDasharray="3 5"/><XAxis dataKey="date" tick={{fontSize:10}} minTickGap={40}/><YAxis unit="%" tick={{fontSize:10}}/><Tooltip formatter={(v:number)=>`${v.toFixed(2)}%`}/><Legend/>{performance.symbols.map((s,i)=><Line key={s} dataKey={s} stroke={colors[i]} dot={false} type="linear"/>)}</LineChart></ResponsiveContainer></div>:!busy&&<p className="text-sm text-muted-foreground">No hay suficientes sesiones comunes para comparar.</p>}
 {!!data?.missing.length&&<p className="text-xs text-amber-300">Sin histórico: {data.missing.join(', ')}.</p>}{!!performance.excluded.length&&<p className="text-xs text-amber-300">No se comparan monedas distintas: {performance.excluded.join(', ')}.</p>}
 <p className="text-[11px] text-muted-foreground">Misma fecha inicial y sesiones comunes; precios ajustados por dividendos y desdoblamientos. SPY representa al S&P 500; los ETF sectoriales son referencias, con comisiones y diferencias frente al índice.{performance.rows.length>0&&` Período efectivo: ${performance.rows[0].date} – ${last?.date}.`}</p></section></>;
}
