import {useState} from 'react';
import {Activity,TrendingDown,BarChart3,MoveVertical} from 'lucide-react';
import {ResponsiveContainer,ComposedChart,Area,Line,Bar,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import type {RiskData} from '../../../supabase/functions/analyze-ticker/asset-risk';
const fmt=(v:number|null|undefined,suffix='')=>v==null?'—':v.toLocaleString('es-ES',{maximumFractionDigits:2})+suffix;
const tabs={vol20:'Volatilidad',drawdown:'Caída desde máximos',volumeRatio:'Volumen relativo',atrPercent:'Rango diario'};
export default function AssetRisk({data,busy,error}:{data?:RiskData;busy:boolean;error:string}){
 const [metric,setMetric]=useState<keyof typeof tabs>('vol20'),[days,setDays]=useState(252);
 const last=data?.history.at(-1),history=data?.history.slice(-days)??[];
 const cards=[{key:'vol20',title:'VOLATILIDAD',icon:Activity,value:fmt(last?.vol20,'%'),detail:`20 sesiones · 60 sesiones: ${fmt(last?.vol60,'%')}`,help:'Desviación de rendimientos logarítmicos ajustados, anualizada con 252 sesiones.'},{key:'drawdown',title:'CAÍDA DESDE MÁXIMOS',icon:TrendingDown,value:fmt(last?.drawdown,'%'),detail:last?`${last.belowPeak} sesiones desde el máximo`:'Sin histórico suficiente',help:'Distancia al cierre máximo de las últimas 252 sesiones disponibles. No representa la caída máxima de todo el período.'},{key:'volumeRatio',title:'VOLUMEN RELATIVO',icon:BarChart3,value:fmt(last?.volumeRatio,'×'),detail:'Frente a 20 sesiones anteriores',help:'Volumen de la última sesión cerrada dividido por la media de las 20 anteriores. No identifica flujos institucionales.'},{key:'atrPercent',title:'RANGO MEDIO · ATR 14',icon:MoveVertical,value:fmt(last?.atrPercent,'%'),detail:`${fmt(last?.atr)} ${data?.currency??''} por sesión`,help:'Rango verdadero medio de 14 sesiones con suavizado de Wilder. Incluye los saltos respecto al cierre anterior; no es un límite de pérdidas.'}] as const;
 return <section className="rounded-xl border border-border bg-card overflow-hidden"><div className="px-5 sm:px-6 py-5 border-b border-border flex flex-wrap gap-3 justify-between items-center"><div className="flex gap-3 items-center"><span className="p-2 rounded-lg bg-sky-400/10 text-sky-400"><Activity size={18}/></span><div><h2 className="text-sm font-semibold tracking-wider">RIESGO Y ACTIVIDAD</h2><p className="text-[10px] text-muted-foreground mt-1">{data?.asOf?`CIERRE · ${data.asOf}`:'HISTÓRICO DEL ACTIVO'}</p></div></div>{last&&<span className="text-[10px] rounded-full px-3 py-1 border border-border text-muted-foreground">{data!.history.length} sesiones</span>}</div>
 {error&&<p role="alert" className="p-5 text-sm text-destructive">{error}</p>}{busy&&!data&&<div role="status" className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3 p-5">{cards.map(c=><div key={c.key} className="h-36 rounded-lg bg-muted/50 motion-safe:animate-pulse"/>)}<span className="sr-only">Calculando riesgo histórico…</span></div>}
 {!busy&&!last&&!error&&<p className="p-8 text-sm text-muted-foreground">No hay suficiente histórico diario verificado para este activo.</p>}
 {last&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3 p-5 sm:p-6">{cards.map(c=>{const p=data?.percentiles[c.key],rank=p?.value;return <button key={c.key} title={c.help} aria-pressed={metric===c.key} onClick={()=>setMetric(c.key)} className={`text-left rounded-lg border p-4 transition-colors ${metric===c.key?'border-sky-400/50 bg-sky-400/5':'border-border hover:border-foreground/30'}`}><div className="flex gap-2 items-center text-[10px] tracking-wide text-muted-foreground"><c.icon size={14}/>{c.title}</div><p className="text-3xl font-semibold tabular-nums mt-4">{c.value}</p><p className="text-[10px] text-muted-foreground mt-2 min-h-8">{c.detail}</p><div className="h-1 rounded bg-muted mt-3 overflow-hidden"><div className={`h-full rounded ${rank!=null&&rank>=90?'bg-amber-400':'bg-sky-400'}`} style={{width:rank==null?'0%':`${rank}%`}}/></div><div className="flex justify-between mt-2 text-[10px] text-muted-foreground"><span>Posición histórica</span><span className={rank!=null&&rank>=90?'text-amber-300':''}>{rank==null?'Sin muestra suficiente':`P${Math.round(rank)}`}</span></div></button>;})}</div>
 <div className="px-5 sm:px-6 pb-6"><div className="flex flex-wrap justify-between gap-3 items-center mb-4"><h3 className="text-xs font-semibold uppercase tracking-wide">{tabs[metric]}</h3><div className="flex gap-1">{[63,126,252].map(n=><button key={n} aria-pressed={days===n} onClick={()=>setDays(n)} className={`text-[10px] px-3 py-2 rounded ${days===n?'bg-muted text-foreground':'text-muted-foreground'}`}>{n===63?'3 MESES':n===126?'6 MESES':'1 AÑO'}</button>)}</div></div>
 <div className="h-64 sm:h-72"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={history}><CartesianGrid stroke="#23302e" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="date" minTickGap={45} tick={{fontSize:10}} tickFormatter={v=>String(v).slice(5)}/><YAxis tick={{fontSize:10}} unit={metric==='volumeRatio'?'×':'%'}/><Tooltip contentStyle={{background:'#101815',border:'1px solid #304239',borderRadius:8}} formatter={(v:number)=>fmt(v,metric==='volumeRatio'?'×':'%')}/>{metric==='vol20'?<><Legend/><Line name="20 sesiones" dataKey="vol20" stroke="#38bdf8" dot={false} strokeWidth={2}/><Line name="60 sesiones" dataKey="vol60" stroke="#a78bfa" dot={false} strokeWidth={1.5}/></>:metric==='volumeRatio'?<Bar name="Volumen relativo" dataKey="volumeRatio" fill="#38bdf8" opacity={.75}/>:<Area name={tabs[metric]} dataKey={metric} stroke={metric==='drawdown'?'#fbbf24':'#34d399'} fill={metric==='drawdown'?'#fbbf24':'#34d399'} fillOpacity={.08} strokeWidth={2}/>}</ComposedChart></ResponsiveContainer></div>
 <div className="mt-4 border-t border-border pt-3 text-[11px] text-muted-foreground leading-relaxed">{cards.find(c=>c.key===metric)?.help} <span className="text-foreground/70">{data?.percentiles[metric]?.value!=null?`P${Math.round(data.percentiles[metric].value!)}: posición frente a ${data.percentiles[metric].samples} observaciones anteriores.`:'El percentil requiere al menos 60 observaciones anteriores.'}</span> {metric==='drawdown'?'Un percentil alto indica una caída más profunda.':'Un percentil alto indica un nivel históricamente elevado.'}</div></div></>}
 </section>;
}
