import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {accountApi} from '@/lib/beta-api';
type Alert={id:string;symbol:string;kind:string;threshold:number;triggered_at:string|null;observed_value:number|null;observed_at:string|null};
const names:Record<string,string>={price_above:'Precio igual o superior a',price_below:'Precio igual o inferior a',daily_up:'Subida diaria de al menos',daily_down:'Caída diaria de al menos',volume:'Volumen diario superior a'};
const unit=(kind:string)=>kind==='volume'?'× la media de 20 sesiones':kind.startsWith('daily')?'%':'';
export function AlertMonitor(){
 useEffect(()=>{let busy=false,last=0,active=true;
 const check=async()=>{if(busy||document.visibilityState==='hidden'||Date.now()-last<60000)return;busy=true;last=Date.now();try{const result=await accountApi<{triggered:Alert[]}>('checkAlerts');if(!active)return;for(const a of result.triggered)toast(`${a.symbol}: ${names[a.kind]} ${a.threshold} ${unit(a.kind)}`,{description:'Alerta activada. Puedes consultar el detalle en la ficha del activo.',duration:15000});window.dispatchEvent(new Event('asset-alerts-checked'));}catch{/* A manual refresh in the alert panel exposes errors. */}finally{busy=false;}};
 void check();const timer=window.setInterval(check,300000);document.addEventListener('visibilitychange',check);return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',check);};
 },[]);return null;
}
export default function AssetAlerts({symbol,currency}:{symbol:string;currency:string}){
 const [alerts,setAlerts]=useState<Alert[]>([]),[kind,setKind]=useState('price_above'),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState('');
 const load=async()=>{const rows=await accountApi<Alert[]>('listAlerts');setAlerts(rows.filter(a=>a.symbol===symbol));};
 useEffect(()=>{let active=true;const refresh=()=>accountApi<Alert[]>('listAlerts').then(rows=>{if(active)setAlerts(rows.filter(a=>a.symbol===symbol));}).catch(()=>{if(active)setError('No se han podido cargar tus alertas.');});void refresh();window.addEventListener('asset-alerts-checked',refresh);return()=>{active=false;window.removeEventListener('asset-alerts-checked',refresh);};},[symbol]);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo completar la operación.');}finally{setBusy(false);}};
 return <section className="rounded-lg border border-border bg-card p-5 space-y-4"><h2 className="text-sm font-semibold">MIS ALERTAS · {symbol}</h2><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void run(async()=>{await accountApi('createAlert',{symbol,kind,threshold:Number(value)});setValue('');});}}><select aria-label="Tipo de alerta" value={kind} onChange={e=>setKind(e.target.value)} className="bg-background border border-border rounded p-2 text-xs">{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input aria-label="Umbral de alerta" type="number" min="0.000001" max="999999999" step="any" required value={value} onChange={e=>setValue(e.target.value)} className="w-28 bg-background border border-border rounded p-2 text-xs"/><span className="text-xs self-center text-muted-foreground">{kind.startsWith('price')?currency:unit(kind)}</span><button disabled={busy} className="px-3 py-2 bg-primary text-primary-foreground rounded text-xs disabled:opacity-50">Crear alerta</button></form>
 <p className="text-xs text-muted-foreground">Guardadas en tu cuenta. Se comprueban cada 5 minutos con la terminal abierta y visible, y al volver a ella. Cada alerta se activa una vez. Las cotizaciones pueden tener retraso.</p><p className="text-[11px] text-muted-foreground">El volumen compara el acumulado de la sesión con la media de 20 sesiones completas; no mide compras institucionales. Máximo 20 alertas pendientes por cuenta.</p>
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 <div className="space-y-2">{alerts.map(a=><div key={a.id} className="border border-border rounded p-3 flex justify-between gap-3 text-xs"><div><b className={a.triggered_at?'text-amber-300':'text-primary'}>{a.triggered_at?'ACTIVADA':'PENDIENTE'}</b><p className="mt-1">{names[a.kind]} {a.threshold} {a.kind.startsWith('price')?currency:unit(a.kind)}</p>{a.triggered_at&&<p className="text-muted-foreground mt-1">Detectada: {new Date(a.triggered_at).toLocaleString('es-ES')} · Valor: {a.observed_value?.toLocaleString('es-ES',{maximumFractionDigits:2})}{a.observed_at&&` · Cotización: ${new Date(a.observed_at).toLocaleString('es-ES')}`}</p>}</div><button disabled={busy} aria-label={`Eliminar alerta ${a.threshold}`} onClick={()=>void run(async()=>{await accountApi('deleteAlert',{id:a.id});})} className="text-muted-foreground hover:text-destructive">Eliminar</button></div>)}{!alerts.length&&<p className="text-sm text-muted-foreground">Todavía no tienes alertas para este activo.</p>}</div>
 <button disabled={busy} className="text-xs text-primary" onClick={()=>void run(async()=>{const result=await accountApi<{checkedAt:string;unavailable:string[]}>('checkAlerts');setChecked(new Date(result.checkedAt).toLocaleTimeString('es-ES'));if(result.unavailable.includes(symbol))setError('No hay una cotización reciente disponible para comprobar este activo.');})}>Comprobar ahora</button>{checked&&<span className="text-xs text-muted-foreground ml-3">Última comprobación: {checked}</span>}
 </section>;
}
